### ISSUE TITLE
Luxon update

### ISSUE THREAD

**Issue by GiuseppeTG** [masangana/es6#1]
### Hello @masangana 👋 

Congrats, your project looks good!

## Highlights

✔️  Clean code
✔️  No linter errors

## Update your date and time

You are not properly importing the luxon date and time. It should be imported as follows:
`import { DateTime } from './luxon.js';`

https://github.com/masangana/es6/blob/3219b34ca1e497b9e42a0b943e673aeedf0ccb85/time.js#L1-L7

## Script tags

You should have just a script for your index.js file to wich you import all other js code from your modules. You have every file as a module script:
https://github.com/masangana/es6/blob/3219b34ca1e497b9e42a0b943e673aeedf0ccb85/index.html#L116-L125

**Comment by masangana** [comment]
thanks for your feedback
